FROM nvidia/cuda:12.1.0-runtime-ubuntu22.04

WORKDIR /app

RUN apt-get update && apt-get install -y python3-pip && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip setuptools wheel

COPY requirements.anone.txt .
RUN pip install --no-cache-dir -r requirements.anone.txt

COPY anone_api.py .

EXPOSE 8080

CMD ["python3", "anone_api.py"]
